//
//  DescInteractor.swift
//  CleanSwiftArchitecture
//
//  Created by cw-james on 2022/03/29.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DescBusinessLogic
{
  func doSomething(request: Desc.Something.Request)
}

protocol DescDataStore
{
  //var name: String { get set }
}

class DescInteractor: DescBusinessLogic, DescDataStore
{
  var presenter: DescPresentationLogic?
  var worker: DescWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Desc.Something.Request)
  {
    worker = DescWorker()
    worker?.doSomeWork()
    
    let response = Desc.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
