# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleanSwiftArchitecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CleanSwiftArchitecture
  pod 'Alamofire'

  target 'CleanSwiftArchitectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CleanSwiftArchitectureUITests' do
    # Pods for testing
  end

end
