//
//  HomeWorker.swift
//  CleanSwiftArchitecture
//
//  Created by cw-james on 2022/03/29.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
    let worker: DefaultNetworkService?
    
    func doSomeWork() {
        worker = DefaultNetworkService(config: "serverURL")
        worker?.request(endPoint: "", headers: "", params: "", completion: nil)
    }
}
