//
//  HomeWorker.swift
//  CleanSwiftArchitecture
//
//  Created by cw-james on 2022/03/29.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
    var repository: PopupRepositoryProtocol?
    
    func fetchPopups(placement: String, completion: @escaping ([Popup]) -> Void) {
        repository?.requestPopupList(completion: { result in
            switch result {
            case .success(let object):
                let popups = object.map { $0.toPopup() }
                completion(popups)
            
            case .failure(let error):
                print(error.localizedDescription)
                completion([])
            }
        })
    }
}
