//
//  HomeRouter.swift
//  CleanSwiftArchitecture
//
//  Created by cw-james on 2022/03/29.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeRoutingLogic {
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject {
    // MARK: Variables
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?

    // MARK: Navigation
//    func navigateToSomewhere(source: HomeViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
}

// MARK: - RoutingLogic Protocol
extension HomeRouter: HomeRoutingLogic {
}

// MARK: - DataPassing Protocol
extension HomeRouter: HomeDataPassing {
}
