//
//  HomePresenter.swift
//  CleanSwiftArchitecture
//
//  Created by cw-james on 2022/03/29.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentPopup(response: Home.ShowPopoup.Response)
}

class HomePresenter {
    // MARK: Variables
    weak var viewController: HomeDisplayLogic?
}

// MARK: - PresentationLogic Protocol
extension HomePresenter: HomePresentationLogic {
    // MARK: Do something
    func presentPopup(response: Home.ShowPopoup.Response) {
        let viewModel = Home.ShowPopoup.ViewModel(popups: response.popups)
        viewController?.displayPopup(viewModel: viewModel)
    }
}
