//
//  HomeModels.swift
//  CleanSwiftArchitecture
//
//  Created by cw-james on 2022/03/29.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    // MARK: Use cases
    enum ShowPopoup {
        struct Request {
            var placement: String
        }
        
        struct Response {
            var popups: [Popup]
        }
        
        struct ViewModel {
            var popups: [Popup]
        }
    }
}
