//
//  HomeRouter.swift
//  CleanSwiftArchitecture
//
//  Created by cw-james on 2022/03/29.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
//    func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject {
    // MARK: Variables
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?

    // MARK: Navigation
//    func navigateToSomewhere(source: HomeViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
}

// MARK: - RoutingLogic Protocol
extension HomeRouter: HomeRoutingLogic {
//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
//    }
}

// MARK: - DataPassing Protocol
extension HomeRouter: HomeDataPassing {
//    func passDataToSomewhere(source: HomeDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
